"""report_service.py — generates real downloadable PDF and CSV reports
for the dashboard's 'Download report' features (reportlab + stdlib csv)."""
import csv
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (Paragraph, SimpleDocTemplate, Spacer, Table,
                                 TableStyle)

FEATURE_ORDER = ["nHM", "piPC09", "PCD", "X2Av", "MLOGP", "ON1V", "N-072", "B02[C-N]", "F04[C-O]"]


def build_pdf_report(record, deployed_model_name: str = "the deployed model") -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm,
                             leftMargin=20 * mm, rightMargin=20 * mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], textColor=colors.HexColor("#0b2a43"))
    elems = []

    elems.append(Paragraph("AquaTox AI &mdash; Fish Toxicity Report", title_style))
    elems.append(Spacer(1, 4))
    elems.append(Paragraph(f"Generated {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} &middot; Record #{record.id}", styles["Normal"]))
    elems.append(Spacer(1, 14))

    compound_line = record.compound_name or "Custom profile"
    if record.cas:
        compound_line += f"  (CAS {record.cas})"
    elems.append(Paragraph(compound_line, styles["Heading2"]))

    is_dangerous = record.prediction == "dangerous"
    verdict = "TOXIC" if is_dangerous else "SAFE"
    confidence = (record.probability if is_dangerous else 1 - record.probability) * 100
    verdict_color = colors.HexColor("#b91c3c") if is_dangerous else colors.HexColor("#0f9d68")
    verdict_style = ParagraphStyle("Verdict", parent=styles["Heading1"], textColor=verdict_color, spaceAfter=4)
    elems.append(Paragraph(f"Verdict: {verdict} &nbsp;&nbsp; Confidence: {confidence:.1f}%", verdict_style))
    elems.append(Spacer(1, 10))

    inputs = record.inputs or {}
    data = [["Molecular descriptor", "Value"]] + [[k, str(inputs.get(k, "—"))] for k in FEATURE_ORDER]
    t = Table(data, colWidths=[260, 200])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#124a6b")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elems.append(t)
    elems.append(Spacer(1, 16))

    elems.append(Paragraph(f"Top contributing factors (SHAP values, deployed {deployed_model_name})", styles["Heading3"]))
    factor_rows = [["Descriptor", "Contribution", "Direction"]]
    for f in (record.top_factors or [])[:5]:
        direction = "toward toxic" if f["contribution"] > 0 else "toward safe"
        factor_rows.append([f["feature"], f"{f['contribution']:.4f}", direction])
    t2 = Table(factor_rows, colWidths=[160, 150, 150])
    t2.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#124a6b")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
    ]))
    elems.append(t2)
    elems.append(Spacer(1, 14))

    if record.true_class is not None:
        true_label = "Safe" if record.true_class == 3 else "Dangerous"
        agree = "agrees with" if true_label.lower() == record.prediction.replace("dangerous", "dangerous") and (
            (true_label == "Safe" and record.prediction == "safe") or (true_label == "Dangerous" and record.prediction == "dangerous")
        ) else "disagrees with"
        elems.append(Paragraph(
            f"Dataset ground-truth label: Class {record.true_class} &rarr; {true_label}. "
            f"The model's prediction {agree} the dataset label.",
            styles["Normal"],
        ))
        elems.append(Spacer(1, 10))

    note = (
        f"Generated by a {deployed_model_name} (StandardScaler &rarr; SMOTE &rarr; {deployed_model_name}, "
        "GridSearchCV-tuned, selected automatically for highest F1 among Logistic Regression / Random Forest / "
        "XGBoost) trained on the QSAR fish bioconcentration dataset — 779 chemicals, 9 Dragon molecular "
        "descriptors. Educational / portfolio demo — not a substitute for regulatory ecotoxicological assessment."
    )
    elems.append(Paragraph(note, styles["Italic"]))

    doc.build(elems)
    return buf.getvalue()


def build_csv_export(rows) -> bytes:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow([
        "id", "timestamp", "compound_name", "cas", "source", "prediction",
        "probability_dangerous", "confidence_pct", "true_class",
    ] + FEATURE_ORDER)
    for r in rows:
        confidence = (r.probability if r.prediction == "dangerous" else 1 - r.probability) * 100
        inputs = r.inputs or {}
        writer.writerow([
            r.id, r.timestamp.isoformat(), r.compound_name, r.cas, r.source, r.prediction,
            f"{r.probability:.4f}", f"{confidence:.1f}", r.true_class,
        ] + [inputs.get(f, "") for f in FEATURE_ORDER])
    return buf.getvalue().encode("utf-8")
